let fname: string = "Natnaris";
let lname: string ="Sangrung";
let age: number =19;
let dream: string ="Programmer"; 
let course: string ="Object-oriented Programming";
let mark1 : number = 83;
let mark2 : number = 70;
let total: number = mark1-mark2;
let pass : boolean = true;

console.log("Name: %s %s \nAge: %d\nDream job: %s \nCourse: %s \nMark: %d",fname,lname,age,dream,course,total);
console.log("Pass",pass);
let courses: string[] =["Databate","Programming","Wed"];
let marks: number[]=[75,72,81];
console.log(marks);
console.log("\n");
console.log(courses[0],marks[0]);
console.log(courses[1],marks[1]);
console.log(courses[2],marks[2]);
console.log("Total Marks: %s",marks[0]+marks[1]+marks[2]);
console.log("Average: %s",(marks[0]+marks[1]+marks[2])/3);